### ISSUE TITLE
Help Improve Flappy Bird - Hacktoberfest

### ISSUE THREAD

**Issue by bitsandbytes1708** [bitsandbytes1708/FlappyBirdClone#1]
Hello everyone! I hope at least on beginner sees this :) 
If you want to contribute towards hacktober, this is a great repository to do it! I have made a basic flappy bird clone, and I would like to see what improvements people can make!
NOTE - I said this is a good Hacktoberfest repository, and it is, but if you just fix a typo or something I will NOT accept your pull request. Please be kind and don't just spam me. Here are some ideas if you can't think of anything to improve - 

Add a way to click and go up instead of just using the up arrow
Improve graphics (highly needed)
Add a way to choose different "skins"
Make a settings page
Make a play button so the game doesn't start immediately
Make a cloud leaderboard(advanced)
Make a way to see your "highscore"
Etc.

**Comment by TalBachar** [comment]
Hi! I would like to help :)

I was able to change it so that you could click to go up, instead of using the keyboard.
I will try to create a "play" button, and also add a "play again" when player loses.

**Comment by ChristineJ82** [comment]
Hello. I would like to help. Let me look into this further tomorrow to see what I can do.

**Comment by TalBachar** [comment]
Until @bitsandbytes1708 replies: I added a "Play Again" button, played around with some of the graphics, and I am working making a "Play" button so the game doesn't start immediately.

**Comment by ChristineJ82** [comment]
@TalBachar thanks for the letting me know what you're working on.

**Comment by bitsandbytes1708** [comment]
@TalBachar Thanks! Can you make a pull request with your changes?

**Comment by bitsandbytes1708** [comment]
@TalBachar Thanks! Is there a way to link a pull request without closing the issue?

**Comment by TalBachar** [comment]
> Is there a way to link a pull request without closing the issue?

I think not. But this gives you a chance to create a new issue with anything else you wish to add / change in the game since the original issue does not apply anymore.

**Comment by bitsandbytes1708** [comment]
@TalBachar Good point, I'll just make a new issue. Thanks a lot! I've updated the repl with your changes. I also moved the canvas and play again button down a bit, but that's the only change I made. Thanks a lot for your help!

**Comment by bitsandbytes1708** [comment]
@ChristineJ82 I have closed this issue because of TalBachar's contributions. You can still contribute, I'm just moving this over to a new issue.
